### ISSUE TITLE
windows appearing under other windows

### ISSUE THREAD

**Issue by lookfirst** [JulyIGHOR/QtBitcoinTrader#102]
Super minor. On OSX. 1.07.96

When I click the About->Check for updates button, the dialog that says "Your version of Qt Bitcoin Trader is up to date" appears behind the about window instead of on top of it.

The same is true of the 'New Window' button. The password/profie dialog window appears behind the existing open exchange. Also, maybe the title of that button is confusing. Maybe it should say: "Exchanges" or "Profiles"

**Comment by JulyIGHOR** [comment]
Can you confirm it fixed?
