### ISSUE TITLE
add OKcoin

### ISSUE THREAD

**Issue by algazarra** [JulyIGHOR/QtBitcoinTrader#145]
please add support for OKCoin. It's by far the largest market right now.

**Comment by btcdrak** [comment]
This has got to be the most important exchange to add right now...

**Comment by cicardia** [comment]
and huobi...

**Comment by btcdrak** [comment]
@cicardia OKCoin is literally *the* most important exchange to add next, by a long long shot. We need support for OKCoin.cn and spot markets (CNY) and okcoin.com USD spot markets, as well as the futures products on .com

**Comment by cicardia** [comment]
yeah... well you should learn that OKCoin has a rather strange way of counting volume... it sure isn't my reference and I'd place huobi ahead.

**Comment by btcdrak** [comment]
@cicardia not the place for such discussions, but fwiw, you are wrong. The chinese exchanges count volume the same way to be consistent with eachother. OKCoin.com counts volume according to the western exchanges status quo. Come into teamspeak or coinmarkets trading channels and speak to hundreds of traders. Less than 1% use Huobi. You are also forgetting about OKCoin.com futures and USD spot exchange. https://bitcoinaverage.com/markets#USD

**Comment by cicardia** [comment]
I can't prove any of this, I just had my doubts confirmed by some of the western exchange's devs. Can you link something to sustain what you say? I'd love to read it
