### ISSUE TITLE
is that a bug? "exchange_indacoin.cpp:638: error: ‘EC_KEY’ was not declared in this scope"

### ISSUE THREAD

**Issue by PatrickPeter** [JulyIGHOR/QtBitcoinTrader#162]
I clone the latest version and compile the code, but some errors are thrown as below:

<pre>
exchange_indacoin.cpp:34:27: error: openssl/ecdsa.h: No such file or directory
exchange_indacoin.cpp: In member function ‘QByteArray Exchange_Indacoin::ecdsaSha1(QByteArray, QByteArray&)’:
exchange_indacoin.cpp:638: error: ‘EC_KEY’ was not declared in this scope
exchange_indacoin.cpp:638: error: ‘eckey’ was not declared in this scope
exchange_indacoin.cpp:638: error: ‘EC_KEY_new_by_curve_name’ was not declared in this scope
exchange_indacoin.cpp:639: error: ‘EC_KEY_generate_key’ was not declared in this scope
exchange_indacoin.cpp:643: error: ‘EC_KEY_set_private_key’ was not declared in this scope
exchange_indacoin.cpp:645: error: ‘ECDSA_size’ was not declared in this scope
exchange_indacoin.cpp:647: error: ‘ECDSA_sign’ was not declared in this scope
make: *** [.obj/exchange_indacoin.o] Error 1
</pre>

I want to ignore these errors caused by indacoin, so I clone the older version 20d3fa6ffd8f90e82c5f47752913690049283ae8 at Sep 25, 2014, and just compile the code. 
To my surprise, it works fine.

**Comment by PatrickPeter** [comment]
Hi man,

Thank you for your reply before. But I don't know which version for openssl
should be installed.

At first, my openssl version is "OpenSSL 0.9.8e-fips-rhel5". There's not a
file called "ecdsa.h" under the directory 'ssl/include/openssl'.

Second, I installed the latest version (OpenSSL 1.0.1j) openssl, and then I
linked the openssl.

but an error was thrown: undefined reference to `EC_KEY_new_by_curve_name'

I found that EC_KEY_new_by_curve_name was defined in "/openssl/ec.h".

so, I just include this file in exchange_indacoin.cpp, unfortunately, the
error still exists as above.

2014-12-26 11:43 GMT+08:00 IGHOR <notifications@github.com>:

**Comment by JulyIGHOR** [comment]
Tell me your OS and what you have done to compile Qt Bitcoin Trader.
I'll try to reproduce this and make fix.

**Comment by PatrickPeter** [comment]
* OS: "CentOS release 5.5 (Final)" 
* qmake: "QMake version 2.01a", and " Qt version 4.8.6"
* openssl: "OpenSSL 1.0.1j 15 Oct 2014"

I just clone the latest version of QtBitcoinTrader. Then,
<pre>
cd src/
qmake QtBitcoinTrader_Desktop.pro
make
</pre>

the older version ( 20d3fa6ffd8f90e82c5f47752913690049283ae8 at Sep 25, 2014) of QtBitcoinTrader was compiled and worked very well.

**Comment by JulyIGHOR** [comment]
https://bitcointalk.org/index.php?topic=85228.0
