### ISSUE TITLE
No market data at Bitcurex

### ISSUE THREAD

**Issue by vlogic2000** [JulyIGHOR/QtBitcoinTrader#168]
Hi.
I tried to use your software at Bitcurex. It has a problems getting data of market. It shows my open orders and last transactions but in "Market" area thera are only zeros.

Can you fix this ?
![qtbt](https://cloud.githubusercontent.com/assets/13062642/8374733/29ffa392-1bf8-11e5-956d-ec227ab149d5.JPG)

**Comment by haeli05** [comment]
Hi, 
The code’s not supposed to work, I just cloned it yesterday. Didn’t mean to publish it, its also very far off from being finished. 
Use Centrabit’s bitcoinQT. 

-- 


On June 26, 2015 at 17:40:51, vlogic2000 (notifications@github.com) wrote:

Hi.
I tried to use your software at Bitcurex. It has a problems getting data of market. It shows my open orders and last transactions but in "Market" area thera are only zeros.

Can you fix this ?

**Comment by JulyIGHOR** [comment]
You need to enable API keys on website, if problem remains than contact Bitcurex, if problem on software side, they will contact me with details how to fix it.

**Comment by JulyIGHOR** [comment]
You can press Alt+Shift+D to inspect problem.
Most of issues came with large ping of Internet provider.
So you can edit config to make longer timeouts.
