### ISSUE TITLE
Orderbook Sorting calculates wrong

### ISSUE THREAD

**Issue by noideal** [JulyIGHOR/QtBitcoinTrader#169]
![2015-08-18 13_36_30-order book bfx](https://cloud.githubusercontent.com/assets/12157720/9340695/9a203a1c-45ae-11e5-82be-1038c67afa81.png)
![2015-08-18 13_36_10-order book bfx](https://cloud.githubusercontent.com/assets/12157720/9340694/9a1fca8c-45ae-11e5-8f82-e942a54a8996.png)

**Comment by JulyIGHOR** [comment]
Can you please explain where is problem?
First row is copy of not grouped orderbook just for visual understanding.

**Comment by noideal** [comment]
I think it's just a matter of the direction in which the prices are listed. That 1000btc order @ 253.01 isn't represented in the grouping at all because it's only adding < 252. I think ideally the asks should be calculated down, while the bids should be calculated up. This isn't really a bug as much as something that would represent the order book better in the grouping.

On a side note: You may see a big increase in downloads soon because your app was the saving grace for some traders on the Bitfinex market margin cascade today. It was talked about a lot in the WhaleClub teamspeak with one of the bfx devs.
I've been using QTT for about 2 years now and everything you've done with it is fantastic!
