### ISSUE TITLE
Еще список багов

### ISSUE THREAD

**Issue by pww2000** [JulyIGHOR/QtBitcoinTrader#171]
1.  Удаляет файл скрипта при удалении из программы!!!!!!
2.  Кнопка "очистить" очищает скрипт не спрашивая подтверждения без возможности отмены (может её убрать с вкладки "Исходный код"???).
3.  Ругается на синтаксис при наличии {} и пользовательских событий в закомментированных строках:
   
   trader.on("Time").changed(){
   a=1;  trader.log(a);
   // если убрать эту строку, то ошибка исчезнет}
   }
4.  Если в процессе работы натыкается на неопределенную переменную, ошибки не выдает, не выполняет дальнейшие команды, делает вид что работает:
   
   trader.on("Time").changed(){
     a=1
     if (trader.get("OpenBidsCount")!=0){aaa()}
     trader.log(a);
   }
   function  aaa(){a=b;trader.log("ничего не выводим:)");}
   //теперь, если после запуска добавить ордер покупки, то функция aaa() ничего не выведет.
5.  Пароль на запуск очень мешает (не представляю, для чего он нужен).
6.  trader.log не выводит отрицательные дробные числа: trader.log(-0.25) выводит 0.
7.  На вкладке "История моих сделок" видит не все сделки (очень похоже, что берет инфу из уведомлений).
8.  trader.delay не срабатывает, если нет кавычек, невозможно использовать команды с кавычками.
9.  Пользовательское событие надо хоть один раз запустить, иначе зависает при проверке
10. Некорректно работает trader.groupStop (не сразу останавливает сам себя):

//этот скрипт называется "tst2"
  trader.groupStop("tst2");
  trader.log("тут скрипт должен уже остановиться");
  trader.log("но он продолжает работать,");
  trader.log("работать,");
 trader.log("и работать:)");

 11 .  Некорректно работает trader.get("BidsPrice",v)
при v < чем объем верхнего ордера в стакане выдает ошибку:"Warning! OrderBook info is out of range. OrderBook information is limited to rows count limit." (результат возвращает вроде правильный)

**Comment by JulyIGHOR** [comment]
1. так задумано
2. после очистки в редакторе работает отмена, Ctrl+Z, следственно потери не будет
3. исправим
5. пароль используется для шифрования локальных данных, это мера безопасности
6. исправлено
7. не все биржы дают возможность подгружать больше истории своих сделок
10. возможно уже исправлено
11. исправлено
