### ISSUE TITLE
Rules have sometimes wrong data.

### ISSUE THREAD

**Issue by gryffus** [JulyIGHOR/QtBitcoinTrader#175]
Testing on BitMarket
When the new value is rounded, the scripting engine still returns the old value.

For example: 

When old AskPrice is 400.1234 and the new value is 400.555
trader.get("AskPrice") returns 400.1234 instead of 400.555.

**Comment by JulyIGHOR** [comment]
I can't reproduce bug, can you provide more info or exact steps how to reproduce it?

**Comment by gryffus** [comment]
With this simple script:
trader.on("Time").changed()
{
 trader.log("BidPrice: "+trader.get("BidPrice"));
 trader.log("AskPrice:"+trader.get("AskPrice"));
}

I get this output:
![screenshot_20160402_223524](https://cloud.githubusercontent.com/assets/3164764/14228874/3a561a1e-f924-11e5-93f3-d6fc3776dce2.png)
