### ISSUE TITLE
В Gentoo версия 1.10.01

### ISSUE THREAD

**Issue by mindw00rk** [JulyIGHOR/QtBitcoinTrader#183]
Доброго времени суток! Спасибо за программу! К сожалению, в Генте весьма старая версия :( 
> * app-office/QtBitcoinTrader
     Доступные версии:      ~1.10.01 **9999
     Домашняя страница:     https://github.com/JulyIGHOR/QtBitcoinTrader
     Описание:              Mt.Gox and BTC-e Bitcoin Trading Client

Да и описание))

**Comment by JulyIGHOR** [comment]
Привет. Пока что у нас нет официального релиза под Linux и отношения к релизу в Генте отношения не имеем.
А как появится то будет авто обновление для всех платформ.

**Comment by mindw00rk** [comment]
0_о интересно, откуда в официальных портах взялся сабж)
