### ISSUE TITLE
Poloniex

### ISSUE THREAD

**Issue by Ozhiganov** [JulyIGHOR/QtBitcoinTrader#184]
Приветствую, планируется ли добавление биржи Poloniex ?

**Comment by bonesoul** [comment]
any chances?

**Comment by bcoufal** [comment]
I vote for Poloniex too.

**Comment by NDuma** [comment]
Priority - Deploy based on Coin Pairs & Volume / Users + Latency?

**Comment by voidzero** [comment]
Poloniex would be fantastic
Kraken too

**Comment by JulyIGHOR** [comment]
Done
