### ISSUE TITLE
нужны доработки pro файла для нормальной линковки c mingw(4.9.2) под windows

### ISSUE THREAD

**Issue by kin63camapa** [JulyIGHOR/QtBitcoinTrader#189]
как то так:
win32 {*-g++ {
LIBS -= -lsapi -llibcrypto -llibssl
LIBS += -lws2_32 -lwinmm -llibeay32
DEFINES -= SAPI_ENABLED
#тут надо не убирать сапи, а проверку на наличие sdk чинить. У меня нигде таких хидеров не было, а условие сработало
}}
Только не спрашивайте зачем мне это понадобилось...

**Comment by JulyIGHOR** [comment]
Флаги и особенности связанные с конкретной сборкой Qt должны быть помещены в файл qconfig.pri самой сборки Qt, это не должно быть учтено в pro файлах проектов.
