### ISSUE TITLE
Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by jedi108** [JulyIGHOR/QtBitcoinTrader#190]
julyaes256.cpp:46:12: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     delete evpMdCtx;
            ^
julyaes256.cpp:41:17: warning: ‘evpMdCtx’ has incomplete type
     EVP_MD_CTX* evpMdCtx = EVP_MD_CTX_create();
                 ^
In file included from /usr/include/openssl/evp.h:14:0,
                 from julyaes256.cpp:33:
/usr/include/openssl/ossl_typ.h:92:16: note: forward declaration of ‘struct evp_md_ctx_st’
 typedef struct evp_md_ctx_st EVP_MD_CTX;
                ^
julyaes256.cpp:46:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     delete evpMdCtx;
            ^
julyaes256.cpp: In static member function ‘static QByteArray JulyAES256::encrypt(const QByteArray&, const QByteArray&)’:
julyaes256.cpp:66:12: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     delete evpCipherCtx;
            ^
julyaes256.cpp:56:21: warning: ‘evpCipherCtx’ has incomplete type
     EVP_CIPHER_CTX* evpCipherCtx = EVP_CIPHER_CTX_new();
                     ^
In file included from /usr/include/openssl/evp.h:14:0,
                 from julyaes256.cpp:33:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘struct evp_cipher_ctx_st’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^
julyaes256.cpp:66:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     delete evpCipherCtx;
            ^
julyaes256.cpp: In static member function ‘static QByteArray JulyAES256::decrypt(const QByteArray&, const QByteArray&)’:
julyaes256.cpp:86:12: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     delete evpCipherCtx;
            ^
julyaes256.cpp:76:21: warning: ‘evpCipherCtx’ has incomplete type
     EVP_CIPHER_CTX* evpCipherCtx = EVP_CIPHER_CTX_new();
                     ^
In file included from /usr/include/openssl/evp.h:14:0,
                 from julyaes256.cpp:33:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘struct evp_cipher_ctx_st’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^
julyaes256.cpp:86:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     delete evpCipherCtx;
            ^
Makefile:2969: ошибка выполнения рецепта для цели «.obj/julyaes256.o»
make: *** [.obj/julyaes256.o] Ошибка 1

**Comment by JulyIGHOR** [comment]
What is your OpenSSL version?

**Comment by COLABORATI** [comment]
I got the same error on Ubuntu 16.04, I have got this ssl dev package installed from [Ondřej Surý](https://launchpad.net/~ondrej/+archive/ubuntu/php) which is very common for using php. 
```
root@ubuntu:~# aptitude show libssl-dev
Package: libssl-dev                      
State: installed
Automatically installed: no
Multi-Arch: same
Version: 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1
Priority: optional
Section: libdevel
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 7.116 k
Depends: libssl1.1 (= 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1)
Recommends: libssl-doc
Breaks: libssl-dev:i386 (!= 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1)
Replaces: libssl-dev:i386 (< 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1)
Description: Secure Sockets Layer toolkit - development files
 This package is part of the OpenSSL project's implementation of the SSL and TLS cryptographic protocols for secure
 communication over the Internet. 
 
 It contains development libraries, header files, and manpages for libssl and libcrypto.
```

how to compile with that version?

It would be great if the build process checked for the right OpenSSL version and gave some hints if the installed version is not the one required. 

Thank you very much for your attention!

**Comment by JulyIGHOR** [comment]
Qt SDK does not support OpenSSL 1.1.x, you need to use OpenSSL 1.0.X

**Comment by lorien** [comment]
How to use openssl 1.0.x instead of default 1.1.x?

**Comment by JulyIGHOR** [comment]
install package libssl1.0-dev
