### ISSUE TITLE
BitStamp : fee value is 0.0%

### ISSUE THREAD

**Issue by scdias** [JulyIGHOR/QtBitcoinTrader#191]
Running the version 1.30.04 the fee value is show correct (0.25%). If run version 1.40.03 in the same machine with the same config the value is 0.0%

**Comment by JulyIGHOR** [comment]
Which one exchange?

**Comment by scdias** [comment]
BitStamp. BTC/EUR
And in my transaction separator don´t show the trades that i made only the deposit. On 1.30.04 show the deposit and the trades.

**Comment by JulyIGHOR** [comment]
Please go to menu, Debug and enable full traffic log. Save it while you see your transactions wrong.
Send it me here or to email julyighor@gmail.com

**Comment by scdias** [comment]
It seems that the interface api is working fine. Maybe it's something when pass the values for the objects in gui 
[Debug.zip](https://github.com/JulyIGHOR/QtBitcoinTrader/files/1198441/Debug.zip)

**Comment by JulyIGHOR** [comment]
Try v1.40.04 and confirm that bug is fixed now.

**Comment by scdias** [comment]
Now is working fine. Thanks!!!!!
