### ISSUE TITLE
endless loop of Select your Exchange

### ISSUE THREAD

**Issue by Thijxx** [JulyIGHOR/QtBitcoinTrader#198]
No matter what I do, I always end up in a loop of "Select your exchange".
I run Linux but that does not matter, it's the same on my other computer.

I add a market, add API details, click ok, then on the login screen it does not matter what I click, it will always return to the "Select your exchange" screen.

**Comment by Beep6581** [comment]
@Thijxx include the version in your bug report, and make sure you're using the latest version before writing a bug report.

**Comment by Thijxx** [comment]
Absolutely, sorry about that. I should know better.
**1.40.04**

The fix seems to be; restarting the application before using it.
