### ISSUE TITLE
Provide exchange order ID in JL script

### ISSUE THREAD

**Issue by BeastOfBodmin** [JulyIGHOR/QtBitcoinTrader#199]
I can't find out how to view the exchange order IDs.

Therefore please add a function call that will return these data.

I have a simple system that requires knowing this and I can't implement it as a trading system in JL Script.

**Comment by JulyIGHOR** [comment]
Still working on new version of JL script.
You will able to do it, and also fetch all orders to get info of each one in loop.

**Comment by BeastOfBodmin** [comment]
Nice!

**Comment by BeastOfBodmin** [comment]
I thought this was a dupe of #181, so I think it is best if I leave it open.
