### ISSUE TITLE
array of last buys and sells

### ISSUE THREAD

**Issue by DrrMrr** [JulyIGHOR/QtBitcoinTrader#200]
Hi,

Can you make array of last n buys? If my bids are to close together, more buys can be executed in the same time and I only have last myLastBuyPrice. If I could know which buys were executed, I can also set the right Ask price for each of them.

This would be really helpful in this case.

Best regards
Damjan

**Comment by JulyIGHOR** [comment]
Hi, working on new script language, you will able to fetch all trade history items in loop and do anything you want.

**Comment by DrrMrr** [comment]
Super. That would be useful.

**Comment by JulyIGHOR** [comment]
Will be available in new script language
