### ISSUE TITLE
Unsynced balance - Bitfinex

### ISSUE THREAD

**Issue by DrrMrr** [JulyIGHOR/QtBitcoinTrader#204]
Hi,

Can you please check sync isssue with sales on Bitfinex. It seems that balance is not synced with latest on Bitfinex. some are missing. It seems to be the problem if more then one sale hase been made.

I'm testing this on Windows 64bit, version v1.40.09.

![unsynced balance](https://user-images.githubusercontent.com/174676/30802450-ec449536-a1e6-11e7-8060-ef95e614b61e.png)

Best regards
Damjan

**Comment by JulyIGHOR** [comment]
Please let me know if issue still there and open this case again
