### ISSUE TITLE
Bitfinex - can't get LastBuy and LestSell Value

### ISSUE THREAD

**Issue by DrrMrr** [JulyIGHOR/QtBitcoinTrader#209]
Hi,

I can't get anymore the value of my last trades on Bitfinex. I'm trading ETH and USD.

Can you please check.

Best regards
Damjan

**Comment by DrrMrr** [comment]
My Transactions are also empty

Best regards
Damjan

![image](https://user-images.githubusercontent.com/174676/31574776-8a12d324-b0d6-11e7-95c5-25c26211a4d2.png)

**Comment by DrrMrr** [comment]
And it seems, that other pairs looks o.k. I tried BTC/USD, ETH/BTC & LTC/USD

**Comment by JulyIGHOR** [comment]
Hello. Need your help to fix it, please email me at julyighor (a) gmail.com

**Comment by krzynek1** [comment]
Have same problem with executed transactions not apperaing when using bitfinex exchange.

**Comment by DrrMrr** [comment]
Hi Ighor,

Is it possible that you also send me source files for the exefile that you
have send me a while ago?

In latest raspian OS compiling your code works as it should but I have the
same problems, like before on latest windows official build.

Best regards
Damjan

**Comment by JulyIGHOR** [comment]
There is too many modifications made, soon I'll merge code here so everyone will get update.

**Comment by DrrMrr** [comment]
O.k. Thank you for your answer.

Best regards
Damjan

**Comment by JulyIGHOR** [comment]
Fixed
