### ISSUE TITLE
Error while compile on Debian 9 (x86_64)

### ISSUE THREAD

**Issue by ialebedev** [JulyIGHOR/QtBitcoinTrader#210]
Trying to compile the latest version of QT Trader on Debian 9 (x86_64).
The compilation stops with error.

![screenshot_20171024_172058](https://user-images.githubusercontent.com/16067800/31948492-c0a38b8e-b8df-11e7-8522-248c8b9fcd99.png)

**Comment by JulyIGHOR** [comment]
#206
