### ISSUE TITLE
How To QtBT Script Template

### ISSUE THREAD

**Issue by mill99** [JulyIGHOR/QtBitcoinTrader#213]
Hi,

First, thank you very much for your awsome work on QtBT !

I'm looking for any help on "QtBT Script Template".

Have you create on HowTo somewhere ?

I found no info in this post => https://forum.centrabit.com/viewforum.php?f=3

Thank you

Mïll#99

**Comment by JulyIGHOR** [comment]
Hello. You can get script template from Rule generator. Just configure it and press left bottom checkbox to view source code.
