### ISSUE TITLE
Bitstamp bid won't generate

### ISSUE THREAD

**Issue by DrrMrr** [JulyIGHOR/QtBitcoinTrader#217]
Hi,

I've noticed, that bids are not generated in bitstamp. I'm using sub account, but if I make bid order by hand in QT Bitcoin trader then it works. I don't get any errors (below is code output image)

![image](https://user-images.githubusercontent.com/174676/34244948-0bbdad0a-e628-11e7-86c0-f45d1e812fb4.png)

Any idea?

Best regards
Damjan

**Comment by DrrMrr** [comment]
You can find code (only differance is BTC instead of LTC) on my link:
`https://github.com/DrrMrr/qt-bitcoin-trader-scripts-signal-trading`

Like I said, I'm using the code for BTC on Bitfinex and it works, But on Bistamp with LTC, ETH or XRP it doesn't. Output looks o.k., bod no bids get generated in order table. If I then enter bid manually with same API key then it works.

Br
Damjan

**Comment by JulyIGHOR** [comment]
Hello. Actually balance, trades, orderbook events works the same way in all supported exchanges.
It looks like your bud is out of balance, can you check out Debug menu and send me logs of timeline when issue appears?

**Comment by DrrMrr** [comment]
Hello. O.k. I will give reply, when I will try again to buy something. This will be somewhere in 24h.

**Comment by DrrMrr** [comment]
Hello Ighor,

I've attached file, when I tried to buy some XRP on Bitstamp. Do I  have rounding problems?

[2017-12-22 09.23.07.log](https://github.com/JulyIGHOR/QtBitcoinTrader/files/1582068/2017-12-22.09.23.07.log)

Best regards
Damjan

**Comment by JulyIGHOR** [comment]
Yes.
RCV: {"status": "error", "reason": {"__all__": ["You need 354.79150 USD to open that order. You have only 354.00197 USD available. Check your account balance for details."]}}

**Comment by DrrMrr** [comment]
o.k. Thank you. Will correct that. 

Best regards
Damjan
