### ISSUE TITLE
script : action read a text language

### ISSUE THREAD

**Issue by operon** [JulyIGHOR/QtBitcoinTrader#219]
Hello,

What is the "read a text" system in a action script ?

I think is a English language, it is possible to choose a language for this action ?

Thanks for your tools

**Comment by JulyIGHOR** [comment]
It will use speech engine to read the text, how would you call it?

**Comment by operon** [comment]
Hello,

I do not understand the question ?
It seems that the message is read in English while my computer is configured in French.

**Comment by JulyIGHOR** [comment]
Ok, you mean that.
Actually all translations made by community.
You are feel free to go to Settings and press Create translation.
Send me lang file and I'll update French translation.

**Comment by operon** [comment]
No it is not this. Ok for translation of sofware by community.

The issue  is for action in a script : "Read a text". On my computer, the text is read in english. It is possible to read in French ?

**Comment by JulyIGHOR** [comment]
Qt Bitcoin Trader speech engine working by pushing text in to OS's speech engine.
So you have to change speech language it in your OS settings.
