### ISSUE TITLE
Market Bitstamp

### ISSUE THREAD

**Issue by operon** [JulyIGHOR/QtBitcoinTrader#220]
Hello,

I do not understand

In scrips, I use last value, ask value, sell value, .... with a connection to the Bitstamp marketplace.

The values used in the script do not match the values displayed in QT's "market" window.

**Comment by operon** [comment]
In addition:

I use QT with bitstamps sub account and several QT's at the same time

**Comment by JulyIGHOR** [comment]
Can you send script code and screenshots please?

**Comment by JulyIGHOR** [comment]
Need more info, if you available again, please send it here and open issue again
