### ISSUE TITLE
Binance support

### ISSUE THREAD

**Issue by namreg** [JulyIGHOR/QtBitcoinTrader#223]
It would be great add binance support

**Comment by Cam177e** [comment]
+1 pls :)

**Comment by fffixed** [comment]
Need Kraken.com first! :)

**Comment by dlasher** [comment]
+1

**Comment by ElPandaro** [comment]
if someone can help me with integrating lib, i could get it done:

https://github.com/binance-exchange/binacpp
thing is, i fail with the makefile stuff. so if someone can setup the makefiles for linking binacpp lib, this would be a great help.

**Comment by JulyIGHOR** [comment]
Done

**Comment by lookfirst** [comment]
@JulyIGHOR SO happy! Thanks! Not sure if you want a different bug report, but the reported fee amount is not accurate based on my discount of using BnB for fees and I cannot adjust it to another decimal place. For example, suppose my fee is 0.075%, in the UX, I can only set it to 0.07%.

**Comment by tolstijdmitrij** [comment]
Здравствуйте!  Не работают правила для отмены ордеров на Binance. У меня только такая проблема?

**Comment by JulyIghor** [comment]
> Здравствуйте! Не работают правила для отмены ордеров на Binance. У меня только такая проблема?
> [2018-11-21 05.37.53.log](https://github.com/JulyIGHOR/QtBitcoinTrader/files/2606582/2018-11-21.05.37.53.log)

исправлено
