### ISSUE TITLE
window graphic issues

### ISSUE THREAD

**Issue by operon** [JulyIGHOR/QtBitcoinTrader#225]
window graphic issues

1 - window mixture
2 - Lack of horizontal scrolling
![qttrader](https://user-images.githubusercontent.com/7881707/35197282-5c9d859c-fedd-11e7-9251-eca4ef843023.png)

**Comment by JulyIGHOR** [comment]
Panels made by standard Qt widget. All panels will not fits your screen resolution. You should join panels into tabs to get more space.

**Comment by operon** [comment]
OK, thanks your reponse
