### ISSUE TITLE
Yobit API issue

### ISSUE THREAD

**Issue by maxim294** [JulyIGHOR/QtBitcoinTrader#226]
I have tried 3 crypto bots in the last week including yours to use on Yobit, none would work and finally one of the devs said that the Yobit API url needed updating.  I hope this is helpful.  Aside from this hiccup, it's a really nice tool.

**Comment by JulyIGHOR** [comment]
is it works now?

**Comment by JulyIGHOR** [comment]
If it still not works please reply and open issue here
