### ISSUE TITLE
Custom stylesheets in Microsoft Windows 7/10?

### ISSUE THREAD

**Issue by bananakid** [JulyIGHOR/QtBitcoinTrader#229]
Hey, is it possible to load a custom theme stylesheet in Windows 7/10? Like using `QT_CURVE_CONFIGFILE=<%PATH%/theme.qtcurve>` Environment Variable for QtCurve apps? I've tried using QT_STYLE_OVERRIDE=[windowsvista](http://doc.qt.io/qt-5/gallery.html) – didn't work. Maybe there's a way to load QSS/CSS theme stylesheet file by placing it into specific directory and using -stylesheet argument (like described [here](https://github.com/Kojoley/qss-dracula) for QtCreator)? If there's a way just to switch from "Fusion" to "WindowsVista" using some argument without extra hustle – it'll do. I've already tried launching with `QtBitcoinTrader.exe -style-windowsvista`, `QtBitcoinTrader.exe -setstyle="windowsvista"` and so on...

**Comment by JulyIGHOR** [comment]
Just go to Qt Bitcoin Trader data folder.
For Windows: %localappdata%\QtBitcoinTrader, Mac: ~/Application Support/QtBitcoinTrader
Create folder Themes and start Qt Bitcoin Trader, than close it.
.thm files will be created in QtBitcoinTrader/Themes folder, you can edit them to change UI stile as you want.
If you make some good styles you can send it to me and I'll add it as separate theme.
