### ISSUE TITLE
Feature request, general question on contribution

### ISSUE THREAD

**Issue by Tarexx** [JulyIGHOR/QtBitcoinTrader#231]
What does it require to create the neccessary files if i want to add an exchange manually?

**Comment by JulyIGHOR** [comment]
I was working on this, but each exchange have unique differences that requires to add unusual code.
I'll work on "universal" engine that makes possible to add new exchange without recompiling later.

**Comment by Tarexx** [comment]
I essentially have some C/C++ knowledge so essentially i could do it myself. I will look for maybe an API that is working for kucoin and then just use the layout you have used in the other exchanges to create it for this exchange
