### ISSUE TITLE
How build this miracle on windows 10

### ISSUE THREAD

**Issue by designofhumanity** [JulyIGHOR/QtBitcoinTrader#233]
How build this miracle on windows 10
1. I should download openssl myself?
2. Wich version of compiler i should use? Debugger Version?
3. What i should download, install in windows. To compile myself all of this? From scatch folder to working Build (exe)?
Environment viarable?
![image](https://user-images.githubusercontent.com/2714036/38746787-3d2a9560-3f51-11e8-8675-c312e7d46dce.png)

![image](https://user-images.githubusercontent.com/2714036/38746835-62e32c7c-3f51-11e8-89eb-351dccb28374.png)

![image](https://user-images.githubusercontent.com/2714036/38746868-819569aa-3f51-11e8-960a-2ac6abdf4807.png)

![image](https://user-images.githubusercontent.com/2714036/38746946-da1cdefa-3f51-11e8-9546-e6e12d292e16.png)

**Comment by JulyIGHOR** [comment]
You need latest Qt SDK + OpenSSL, easiest to use Qt Creator

**Comment by designofhumanity** [comment]
Легче использовать Кьют Криєйтор, взгляните на скриншоты если не трудно)

**Comment by JulyIGHOR** [comment]
5.10.1 + MinGW 5.3 + Qt Script

**Comment by designofhumanity** [comment]
А где должна лежать папка OpenSSL, и какую версию качать? 
![image](https://user-images.githubusercontent.com/2714036/38751700-82909680-3f61-11e8-9ff2-3641b2466240.png)

![image](https://user-images.githubusercontent.com/2714036/38751716-8e085200-3f61-11e8-8da2-0ccf18813630.png)

**Comment by JulyIGHOR** [comment]
Мы всегда все проверяем для последних версий всех зависимостей.
https://stackoverflow.com/questions/14681012/how-to-include-openssl-in-a-qt-project

**Comment by designofhumanity** [comment]
Опять же я так понимаю нужно ставить и 32 битную и 64 битную версию OpenSSl?
![image](https://user-images.githubusercontent.com/2714036/38946072-018fae5c-4341-11e8-92c0-c35559b48d8e.png)

**Comment by designofhumanity** [comment]
Так же ищет какуюто папку (библиотеку) сrypto и Z
![image](https://user-images.githubusercontent.com/2714036/38946241-88a4db9c-4341-11e8-9cdb-b802e9b15894.png)

**Comment by JulyIGHOR** [comment]
В файл Qt/mkspecs/qconfig.pri надо добавить папки OpenSSL
LIBS += -L"C:/ путь к папке lib"
INCLUDEPATH += "C:/ путь к папке include"
