### ISSUE TITLE
Windows 10 build problem

### ISSUE THREAD

**Issue by highdev2016** [JulyIGHOR/QtBitcoinTrader#236]
Hello,

I've installed latest qt creator and built this project on windows 10.
The build finished successfully and I can see the QtBitcoinTrader_64bit.exe on release folder.
But that exe file could not be executed with this critical error.

![image](https://user-images.githubusercontent.com/23272057/40338113-eca263d4-5da5-11e8-9e79-a1f708a309dc.png)

Is this the dependency problem? 
If not, how can I solve this issue?

Thank you.

**Comment by JulyIGHOR** [comment]
http://doc.qt.io/qt-5/windows-deployment.html

**Comment by KandyYe** [comment]
Would you please help to share the method of building it on Windows 10?
