### ISSUE TITLE
Small spelling mistake

### ISSUE THREAD

**Issue by lookfirst** [JulyIGHOR/QtBitcoinTrader#240]
![image](https://user-images.githubusercontent.com/85355/48174843-2d28ed80-e33c-11e8-92df-051436d4012a.png)

**Comment by lookfirst** [comment]
https://github.com/JulyIGHOR/QtBitcoinTrader/search?q=comparation&unscoped_q=comparation

**Comment by lookfirst** [comment]
Wow, it is a word. Just unusual for me. Sorry about that.

**Comment by JulyIGHOR** [comment]
You are right, I'll fix it in next update
