### ISSUE TITLE
The IP Address Of Qt Bitcoin Trader is needed for Binance higher trading security

### ISSUE THREAD

**Issue by AstralTim67** [JulyIGHOR/QtBitcoinTrader#242]
I just finished linking my Qt Bitcoin Trader account with Binance and one of the added security features of Binance is to "Restrict access to trusted IPs only" (Recommended)  or "Unrestricted" (Less Secure), but I would need the IP address of Qt Bitcoin Trader to use the recommended method.  What is the IP address used for Qt?  Thank you.

**Comment by JulyIGHOR** [comment]
This have no relation to application itself.
You can get your public IP for example by visiting this page https://api.ipify.org
