### ISSUE TITLE
Arch linux AUR - error compilation

### ISSUE THREAD

**Issue by GelmutShmidt** [JulyIghor/QtBitcoinTrader#245]
![image](https://user-images.githubusercontent.com/30620714/52280782-b36dc380-296d-11e9-8877-204b1439aa44.png)
then i install package on my arch i always see errror

**Comment by JulyIghor** [comment]
OpenSSL is missing or wrong version

**Comment by GelmutShmidt** [comment]
what the version of openssl i need ?

**Comment by JulyIghor** [comment]
Open SSL 1.1 or 1.1.1 is preferred
