### ISSUE TITLE
Problem with the Binance account

### ISSUE THREAD

**Issue by Rolboy** [JulyIghor/QtBitcoinTrader#246]
There is a problem with the Binance account. Don't show my trade data and balance. Already changed two APIs, but the problem remains the same. At the same time, with Poliniex everything works without problems.
Qt Bitcoin Trader v1.40.40. on Windows 8.1

**Comment by Rolboy** [comment]
Good news!
After 2 days all problems disappeared. There is no obvious reason, but now the Binance account works well.

**Comment by JulyIghor** [comment]
It looks like time sync problem, will be fixed in upcoming update

**Comment by JulyIghor** [comment]
Fixed
