### ISSUE TITLE
No USDT balance on Binance

### ISSUE THREAD

**Issue by DrrMrr** [JulyIghor/QtBitcoinTrader#247]
Hi,

I have problems with showing my real balance from Binance. It shows that my balance is empty. Is this a known problem?

I Have USDT and zero BTC. I Also have some TUSD and it won't show any balance in any pair.

![slika](https://user-images.githubusercontent.com/174676/52917079-71d30600-32e7-11e9-9a8e-0b66622fb525.png)

I'm using 1.40.40 64bit version on Windows.

Is it possible that also other currencies are not showing any wallet amounts?

Thank you and best regards
Damien

**Comment by JulyIghor** [comment]
Are you sure you use API keys only with single app?
Are you sure API keys have rights?
If yes to both, send traffic captured by Debug menu dialog

**Comment by DrrMrr** [comment]
Hi, yes I have right API keys. USDT value is updating in the right corner.

https://ufile.io/pry14

http://qt.io/download-open-source/ 
![slika](https://user-images.githubusercontent.com/174676/52917459-135c5680-32ec-11e9-9c2b-4d01c3793c01.png)

thank you
Damien

**Comment by DrrMrr** [comment]
Hi,

Like you mentioned. With new API key it works? Don't you check API credentials after login?

Best regards
Damjan

**Comment by JulyIghor** [comment]
If you used the same API key at least once in other apps, it will not work in Qt Bitcoin Trader
API requests can fail in many reasons, that's why app trying to use it again and again.
Please let me know is this build works for you

[QtBitcoinTrader_windows_64bit.zip](https://github.com/JulyIghor/QtBitcoinTrader/files/2885154/QtBitcoinTrader_windows_64bit.zip)

**Comment by DrrMrr** [comment]
Hi,

No, it's still not working. But I have created the first API key only for
QT Bitcoin trader, so no other app uses it.

But, it's o.k., Like I have mentioned on GitHub it works with secondary API
Key for Bitcoin trader.

Best Regards
Damjan
