### ISSUE TITLE
не подключается в YOBiT

### ISSUE THREAD

**Issue by doulsw** [JulyIghor/QtBitcoinTrader#249]
не могу подключиться к YOBIT созданы новые API
![default](https://user-images.githubusercontent.com/47898692/53298479-d3dbc000-383f-11e9-9527-b68f7b926c8e.jpg)

**Comment by JulyIghor** [comment]
Попробуйте увеличить таймаут запросов в настройках.
Если не поможет то пришлите вывод с меню Debug
Так или иначе, если АРІ лаг красный, это не связано с АРІ ключами

**Comment by doulsw** [comment]
Для России работает доступ только по  https://yobitex.net добавьте его

**Comment by JulyIghor** [comment]
добавим

**Comment by JulyIghor** [comment]
Добавлена настройка с альтернативным доменом
