### ISSUE TITLE
Bittrax no "sells" created

### ISSUE THREAD

**Issue by immerzu** [JulyIghor/QtBitcoinTrader#253]
Hi,

when i click on sell, no sales are created at bittrax. The message appears as attached to the screen. I have plenty of coins to sell. This message also appears when only 50% sales are made!

![2019-03-14 18-34-39 Please confirm transaction](https://user-images.githubusercontent.com/19924914/54378757-5067fe80-4688-11e9-8a5b-ae6defb723aa.jpg)

**Comment by JulyIghor** [comment]
Go to Debug menu, and save log that happens in this moment, send me log file please

**Comment by immerzu** [comment]
[2019-03-14 17.41.17.log](https://github.com/JulyIghor/QtBitcoinTrader/files/2967758/2019-03-14.17.41.17.log)

**Comment by immerzu** [comment]
I started debug and then "sell". clicked. once with 50% and once with 100% coins.

**Comment by JulyIghor** [comment]
I have found in log file INVALID_PERMISSION error. So it was wrong API key rights.

**Comment by immerzu** [comment]
That doesn't sound good. I just created the api-Keys today. Will create new Api-Keys and try again. 

Thank you.

**Comment by JulyIghor** [comment]
In some exchanges created API keys have some limited rights and you need to change them after created.

**Comment by immerzu** [comment]
It works now! It was my fault. I didn't give the authorization.

THANK YOU!

**Comment by immerzu** [comment]
![2019-03-14 18-48-19 Bittrex com - Manage Settings - Yandex Browser](https://user-images.githubusercontent.com/19924914/54379524-d89ad380-4689-11e9-9032-fd56399dda28.jpg)
