### ISSUE TITLE
translation errors

### ISSUE THREAD

**Issue by immerzu** [JulyIghor/QtBitcoinTrader#254]
in german

![2019-03-16 16-55-38 ฿ 0 00037391 ↓ edekoko - Qt Bitcoin Trader v1 40 40 (64bit)](https://user-images.githubusercontent.com/19924914/54477882-89c97700-480c-11e9-8395-da74cfd1e52d.jpg)

**Comment by JulyIghor** [comment]
Please go to app Settings and press button "Create translation"
Fix all translation issues in your language and save file.
Send it to me and I'll include it in to upcoming update.

**Comment by immerzu** [comment]
Thanks!

![2019-03-16 17-18-10 ฿ 0 00037494 - edekoko - Qt Bitcoin Trader v1 40 40 (64bit)](https://user-images.githubusercontent.com/19924914/54478157-91d6e600-480f-11e9-8f4f-84983e577508.jpg)

**Comment by JulyIghor** [comment]
Please send translation file to me, so I can share it with others by builtin in to the app

**Comment by immerzu** [comment]
Here you go.
