### ISSUE TITLE
Segmentation fault in Linux Distribution

### ISSUE THREAD

**Issue by scdias** [JulyIghor/QtBitcoinTrader#256]
I got this same error downloading in sourceforge ou building in my pc. 
Commenting the line in the print screen i got the program running ok
Built with Qt 5.12.2.

![Screenshot_20190409_212116](https://user-images.githubusercontent.com/20443295/55832822-4bbf2a80-5b0e-11e9-94ac-3d17bd6f038b.png)

**Comment by JulyIghor** [comment]
Can you please confirm it fixed in latest commit?

**Comment by JulyIghor** [comment]
fixed, thanks for bug report!

**Comment by scdias** [comment]
> Can you please confirm it fixed in latest commit?
It's all fine building in PC
Thanks :)
