### ISSUE TITLE
nonce must be greater than / modal dialog

### ISSUE THREAD

**Issue by ytoto** [JulyIghor/QtBitcoinTrader#260]
Hello,

This is my first try of QtBitcoinTrader and have this error poping up every 0.5 to 10 seconds, so making it practically unusable. I'm testing the win64 version 1.4.0.43 downloaded from sf.net.

The message shows:
nonce must be greater than 'some number > 2^32'.  You provided 'some number < 2^31'

![QtBitconTrader_nonce](https://user-images.githubusercontent.com/4997097/67215589-05824680-f422-11e9-9fd0-0e14eefcfa77.png)

-8<--- the debug log:
2019-10-21 17:00:05 LVL:0
HTTP/1.1 422
Date: Mon, 21 Oct 2019 15:00:05 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
CF-Rate-Limit-Rule-Id: b25469efe9fb4045a37fe9427e8ae460
CF-Rate-Limit-Action: simulate
Retry-After: 118
Cache-Control: private
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5294195f0b23d685-MAD

4e
{"error":"Nonce must be greater than 1507272446735. You provided 1998128012."}

**Comment by JulyIghor** [comment]
This error means that you tried to use the same API keys with other apps.
It is important, one API key pair will work only with one app, and once you run another app, it breaks previous one.
