### ISSUE TITLE
Wrong last price per coin

### ISSUE THREAD

**Issue by Synthacon** [JulyIghor/QtBitcoinTrader#261]
Binance AMB/BTC
If I click Ask, Bit and Last i get:
bid: 0.00000386   ok
ask: 0.00000388 ok

last: 0.01973200 not ok at all

After selecting AMBETH and AMBBNB and then AMBBTC buttos are showing right values.

**Comment by JulyIghor** [comment]
maybe fixed, if not, open ticket again
