### ISSUE TITLE
Fail to open sell orders on binance

### ISSUE THREAD

**Issue by Synthacon** [JulyIghor/QtBitcoinTrader#262]
Selecting "All in" for coins and "Last" for price and hitting SELL, then pressing YES does absolutely nothing.

**Comment by JulyIghor** [comment]
Can you please tell amount that filled in after "All in" button pressed?

**Comment by Synthacon** [comment]
AMB/BTC the amount was  1951 AMB

**Comment by ServidoresJMG** [comment]
yes, this is what happens

Qt Bitcoin Trader 1.40.43
OS: Windows 192
------------------
2019-11-10 14:31:04 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:04 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:04 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:27 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:27 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:27 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:28 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:28 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:28 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:28 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:28 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:28 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:28 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:28 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:29 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:29 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:29 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:29 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:40 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:40 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:40 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:40 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:40 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:40 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:40 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:41 LVL:2
Sell: symbol=ERDUSDT&side=SELL&type=LIMIT&timeInForce=GTC&quantity=22915&price=0.0020785&
------------------


------------------
2019-11-10 14:31:41 LVL:2
Added to Query RetryCount=7
------------------


------------------
2019-11-10 14:31:41 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:42 LVL:2
Sending request ID: 307
------------------


------------------
2019-11-10 14:31:43 LVL:2
Sending request ID: 307
------------------

**Comment by Synthacon** [comment]
Same has happened multiple times with BTC/USDC
Selling everything does absolutely nothing.

**Comment by JulyIghor** [comment]
maybe fixed, if not, open ticket again
