### ISSUE TITLE
Rules not working?

### ISSUE THREAD

**Issue by Synthacon** [JulyIghor/QtBitcoinTrader#264]
I want to beep if last price is >= (grater than or equal) than 7480

Trigger:                                   
Last price
BTC/USDC       
0.0

Operator::   >= 

When condition is true:
Last price
BTC/USDC
7480

I don't understand why there is + - * /  ?! So I leave plus
no tick on the percentage

Then execute action
Beep

And absolutely nothing happens when price is higher than 7480.

**Comment by JulyIghor** [comment]
While you are waiting what is status of that rule?
You can edit rule and while editing press on check box on the left bottom corner, you will see source code of rule that makes you deeply understand what is going on.
If you select plus, it will add selected % or value to the price before comparison.

**Comment by JulyIghor** [comment]
maybe fixed, if not, open ticket again
