### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: texttospeech

### ISSUE THREAD

**Issue by almqq** [JulyIghor/QtBitcoinTrader#266]
Hi, a newbie here.
Just tried to install QtBitcoinTrader, but on this step:

QT_SELECT=5 qmake QtBitcoinTrader_Desktop.pro

I get
Project ERROR: Unknown module(s) in QT: texttospeech

How do  I install this module. I cannot find help anywhere

**Comment by JulyIghor** [comment]
Try to install qt5-default package from your OSs repo

**Comment by almqq** [comment]
Hi, thanks. Still same error. Any other ideas?

>sudo apt-get install qt5-default
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libllvm7 libllvm8
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  qt5-default
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 20.9 kB of archives.
After this operation, 159 kB of additional disk space will be used.
Get:1 http://za.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 qt5-default amd64 5.9.5+dfsg-0ubuntu2.5 [20.9 kB]
Fetched 20.9 kB in 1s (30.6 kB/s)                      
Selecting previously unselected package qt5-default:amd64.
(Reading database ... 191204 files and directories currently installed.)
Preparing to unpack .../qt5-default_5.9.5+dfsg-0ubuntu2.5_amd64.deb ...
Unpacking qt5-default:amd64 (5.9.5+dfsg-0ubuntu2.5) ...
Setting up qt5-default:amd64 (5.9.5+dfsg-0ubuntu2.5) ...

>QT_SELECT=5 qmake QtBitcoinTrader_Desktop.pro
Project ERROR: Unknown module(s) in QT: texttospeech

**Comment by JulyIghor** [comment]
And if you install this one? qtspeech5-speechd-plugin

**Comment by almqq** [comment]
Can't seem to find it.

> sudo apt-get install qtspeech5-speechd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qtspeech5-speechd

**Comment by JulyIghor** [comment]
what is your output of sudo **apt-cache search qtspeech5** ?

**Comment by almqq** [comment]
> sudo apt-cache search qtspeech5
qtspeech5-doc - Speech library for Qt - documentation
qtspeech5-doc-html - Speech library for Qt - HTML documentation
qtspeech5-examples - Speech library for Qt - Examples
qtspeech5-flite-plugin - Speech library for Qt - Flite plugin
amnon@11Calais:~/QtBitcoinTrader/src$

**Comment by JulyIghor** [comment]
try this qtspeech5-flite-plugin

**Comment by almqq** [comment]
I did already! No luck

> sudo apt-get install qtspeech5-flite-plugin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
qtspeech5-flite-plugin is already the newest version (5.9.5-0ubuntu1).
The following packages were automatically installed and are no longer required:
  libllvm7 libllvm8
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

> QT_SELECT=5 qmake QtBitcoinTrader_Desktop.pro
Project ERROR: Unknown module(s) in QT: texttospeech

**Comment by JulyIghor** [comment]
For now you can download official Qt release for example from here https://download.qt.io/official_releases/qt/5.14/5.14.2/qt-opensource-linux-x64-5.14.2.run
When installed it contains all plugins.
Anyway thanks for bug report, I'll inspect how to fix that for a repo Qt version.

**Comment by almqq** [comment]
OK, last stupid question. I have installed the QT Creator from the .run file above. How do I load up the QtBitcoinTrader application?

**Comment by JulyIghor** [comment]
Use File->Open project, and browse to src folder, open .pro file, and compile it in Release mode
By the way, you can use our official x86_64 linux binary https://sourceforge.net/projects/bitcointrader/files/Linux/

**Comment by JulyIghor** [comment]
Hello. You should just open QtBitcoinTrader_Desktop.pro via Qt Creator and press build in release mode.
By the way try to install libqt5texttospeech5-dev some people reported that it worked.
