### ISSUE TITLE
HITBTC api key problem

### ISSUE THREAD

**Issue by piotrwieland2012** [JulyIghor/QtBitcoinTrader#267]
application cannot accept hitbtc API key , other markets working

**Comment by JulyIghor** [comment]
Can you please send me example of your API key? replace it by random symbols, but same length, case and digits placement

**Comment by piotrwieland** [comment]
key:3bVYA6A8TuhBQT0H9GbJu_OV0vrFqg9O
sec:3b1eac34-c8af-4d41-915b-61d7e4803cfa

**Comment by JulyIghor** [comment]
> key:3bVYA6A8TuhBQT0H9GbJu_OV0vrFqg9O
> sec:3b1eac34-c8af-4d41-915b-61d7e4803cfa

just to be sure, are you entering '3bVYA6A8TuhBQT0H9GbJu_OV0vrFqg9O', not 'key:3bVYA6A8TuhBQT0H9GbJu_OV0vrFqg9O' right?

**Comment by piotrwieland** [comment]
100% correct entering keys without "key:" and "sec:"

**Comment by piotrwieland** [comment]
this is a debug mesage from program
------------------
2020-09-11 20:44:25 LVL:0
SND: GET /api/2/trading/fee/BTCUSD HTTP/1.1
User-Agent: Qt Bitcoin Trader v1.40.52
Host: api.hitbtc.com
Accept: */*
Accept-Encoding: gzip
Connection: keep-alive
Authorization: Basic VGRFN01rZzdpMVp4NzFXTkJRcWZRaFA1Z3NmcktpUjc6c1ZRWm9iM1o3b3NhV09XWEcwTDUzMXU0T040b2tFYg==


------------------


------------------
2020-09-11 20:44:25 LVL:0
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Fri, 11 Sep 2020 18:44:25 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 73
Connection: keep-alive

{"error":{"code":1002,"message":"Authorization failed","description":""}}
------------------

**Comment by JulyIghor** [comment]
Thanks, are you sure you give trade rights to those keys?

**Comment by piotrwieland** [comment]
https://drive.google.com/file/d/1pn-Kn0wN9pHfaSgbUTcMSpseYmT-6bCt/view?usp=sharing

**Comment by piotrwieland** [comment]
if i try authorize via , "curl" no problem , and POSTMAN , binance market works correctly

**Comment by piotrwieland** [comment]
curl auth 
https://drive.google.com/file/d/1KCZIJxqoUJpum91IndvrPmA93DQIDn7x/view?usp=sharing

**Comment by JulyIghor** [comment]
looks like they changed api key format, thanks, it will be fixed in upcoming update

**Comment by piotrwieland** [comment]
thank you for your hard work , great application     :-)
