### ISSUE TITLE
Fee on Bitstamp exchange

### ISSUE THREAD

**Issue by operon** [JulyIghor/QtBitcoinTrader#268]
Hello,

It seems that version 1.40.52 no longer collects transaction fees on Bitstamp exchange
cordially

Last change in code ??? : https://github.com/JulyIghor/QtBitcoinTrader/commit/7b3b1132dec923cf6617a4237d88b1a128894747#diff-bedc4c91b886ab81ab1bea2e9054676d72e80e3ace2bd37034c3590746ddb1a7

**Comment by JulyIghor** [comment]
Hello. We have fixed this issue, but update not released yet since we are waiting for a signing certificate renew.
Once we get it the fix will be released.

**Comment by operon** [comment]
Ok thanks for your correction.
