### ISSUE TITLE
Бан на Binance при открытии нескольких окон

### ISSUE THREAD

**Issue by YufinGW** [JulyIghor/QtBitcoinTrader#272]
Какие нужно установить настройки API для 2-3 окон, чтобы не получать бан на binance? В документации binance указано, что должно быть не больше 1200 запросов в минуту.

**Comment by JulyIghor** [comment]
Увеличивайте интервал запросов в столько раз сколько копий программы запущено

**Comment by YufinGW** [comment]
Благодарю
