### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by 12shyrikoff** [JulyIghor/QtBitcoinTrader#273]
Could not install program correctly. When do 

"QT_SELECT=5 qmake QtBitcoinTrader_Desktop.pro"
- Project ERROR: Unknown module(s) in QT: texttospeech

System:
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

qmake version: 
QMake version 3.1
Using Qt version 5.11.3 in /usr/lib/arm-linux-gnueabihf

Could you please say me what I do wrong!

Thanks

**Comment by JulyIghor** [comment]
Hello. You need to install libqt5texttospeech5-dev package

**Comment by 12shyrikoff** [comment]
Thanks a lot! Now it works great! Thank you for your work!
