### ISSUE TITLE
trader.groupStop() command not executing without the (script name) parameter

### ISSUE THREAD

**Issue by rolboy53** [JulyIghor/QtBitcoinTrader#274]
After the update, the trader.groupStop () command not executing without the (script name) parameter to stop the script itself.  The console displays: Stop group "Script-tmp" but the script continues to run.  If you specify the name of the script, then it works.  But earlier it was more convenient to stop yourself with a command without a parameter.

После обновления перестала исполнятся команда trader.groupStop() без параметра (имя скрипта ) для остановки скрипта самого себя. На консоле выводится: Stop group "Script-tmp" но скрипт продолжает работать. Если указать имя скрипта,  тогда работает. Но раньше остановить самого себя командой без параметра было удобнее.

**Comment by JulyIghor** [comment]
thanks, fixed
