### ISSUE TITLE
Невозможно открыть ордер. Изменение шага цены. Binance.

### ISSUE THREAD

**Issue by mxzoom** [JulyIghor/QtBitcoinTrader#276]
С 26/08/21 перестали открываться ордеры на бинансе, через QTBitcoinTrader, похоже, проблема в изменении минимального размера тика, и шага цены на бирже - https://www.binance.com/en/support/announcement/6925d618ab6b47e2936cc4614eaad64b  Релиз - 1.40.55

**Comment by JulyIghor** [comment]
Мы синхронизировали пары. Проверьте еще раз

**Comment by mxzoom** [comment]
> Мы синхронизировали пары. Проверьте еще раз

Не работает. Принудительную синхронизацию пар запускал, автосинхронизация пар при запуске активирована.

**Comment by JulyIghor** [comment]
Через меню откройте диалог Debug, включите лог, попробуйте открыть ордер. После неудачной попытке сохраните лог и пришлите сюда julyighor@gmail.com

**Comment by JulyIghor** [comment]
Спасибо за лог. Синхронизируйте пары еще раз и пробуйте, дайте знать о результатах

**Comment by mxzoom** [comment]
> Спасибо за лог. Синхронизируйте пары еще раз и пробуйте, дайте знать о результатах

Теперь все работает, как ожидалось! Благодарю за быстрое исправление!
