### ISSUE TITLE
which needed version for build windows 10?

### ISSUE THREAD

**Issue by lonestar44** [JulyIghor/QtBitcoinTrader#277]
I tried build that I saw old issues closed #233. but error occur need update Qt 5.10 not supported for [QFontMetrics::horizontalAdvance](https://stackoverflow.com/questions/50864893/qts-qfontmetricshorizontaladvance-missing-for-code-editor-implementation).

updated version Qt 5.12.0 + MinGW 7.3 64bit and [Win64 OpenSSL v1.1.1m](http://slproweb.com/products/Win32OpenSSL.html) can build success but execute segment fault. 

recently your commit 43416904ae10de2ad93914c2f97a3d510b4c1e2e Which Qt, Open SSL, Compiler all of versions using exactly for build success on windows 10 64bit? I think you compile statically option right? Please detail option and version.  

Here is I changed QtBitcoinTrader_Desktop.pro file 
```
win32 {
    LIBS += -llibssl -llibcrypto -lz
    INCLUDEPATH += "D:\OpenSSL-Win64\include"
    LIBS += -L"D:\OpenSSL-Win64\lib"
```

**Comment by JulyIghor** [comment]
Hello.
You need OpenSSL library that built with the same compiler you use.
You can try to compile OpenSSL by your own or find another builds.
Both OpenSSL 1.0 and 1.1 versions supported by Qt Bitcoin Trader.

**Comment by dakshunt** [comment]
Here is my success environment versions and how to way compile for windows 10 64bit version

[Qt 5.12.12](https://download.qt.io/official_releases/qt/5.12/5.12.12/qt-opensource-windows-x86-5.12.12.exe) compiled by 64bit mingw 7.3.0 version 
[OpenSSL official source 1.1.1m](https://www.openssl.org/source/openssl-1.1.1m.tar.gz) 
[MSYS2 64bit](https://github.com/msys2/msys2-installer/releases/download/2021-11-30/msys2-x86_64-20211130.exe)  
```
OpenSSL compile command on MSYS2 console as Administrator execute on Windows 10 Pro 21H2 version (my computer but other version also okay I guess)

1. Install toolchain  

# pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain git subversion mercurial mingw-w64-i686-cmake mingw-w64-x86_64-cmake

now recently gcc version 11.2.0 (Rev2, Built by MSYS2 project)

2. uncompress and make command 

your home directory move and uncompress file like this..

# tar xvzf openssl-1.1.1m.tar.gz
...
# cd openssl-1.1.1m

/C/ mean is install C: drive path
 
# perl Configure mingw64 --prefix=/C/OpenSSL-x64
 OpenSSL has been successfully configured
...

# make depend
check file dependency...

# make -j 16 
-j 16 mean is Multithread compile option depend on your CPU core (my CPU AMD Ryzen 7 2700x 8 core processor model have each core two thread possible 8x2=16)

# make install
install include header, library, dll files on your window system directory thats why need windows administrator permission

3. add lines to QtBitcoinTrader_Desktop.pro file for compile option.

31-34 line block like below this append option.

win32 {
    INCLUDEPATH	+= "C:\OpenSSL-x64\include"
    LIBS += -L"C:\OpenSSL-x64\lib"
    
```

I tried 32bit compile environment but it still failed. If someone succeeds, please reply to this comment.

Good luck!

**Comment by dark4night** [comment]
I did success again for 32bit compile. 

Qt 15.5.2 32bit compile by mingw 8.1.0 32bit
OpenSSL official source 1.1.1m 
```
same source code file like 64bit environment but need compile 32bit compiler option 
# perl Configure mingw --prefix=/C/OpenSSL

.pro file modified

win32 {
    INCLUDEPATH	+= "C:\OpenSSL\include"
    LIBS += -L"C:\OpenSSL\lib"
```
MSYS2 32bit console execute use gcc 11.2.0 32bit version higher version than Qt compiled but I think this no problem for build.

not much different but I choice  Qt 15.5.2 version because include 32bit compiler and environment console setting. 

to @JulyIghor I think good for this summary for wiki page for beginner.
