### ISSUE TITLE
about rules group

### ISSUE THREAD

**Issue by m2m4m6m8m10** [JulyIghor/QtBitcoinTrader#279]
iam i can trade in group rules without use normal trading or not
or group rules trade and normal trade are connected
or group rules trade are not even trade
because i have try more than once to trade through group rules and its not working
so please tell me if rules group trade or not 
and if reles group is trade than tell me how to trade on it
![Screenshot_2](https://user-images.githubusercontent.com/96547465/147614696-bdfda155-9d3c-4eef-91dc-a3e4d8b23e95.png)

**Comment by JulyIghor** [comment]
Hello. You can inspect logs via Debug menu to find out why your order failed, possibly you have not enough balance to fill that. If it is not true, please send Debug logs that recorded during open order attempts here

**Comment by m2m4m6m8m10** [comment]
it was like this since i usd it
is there anything wrong
i know about normal trading
but i want to know if rules group is trading or not
and please if there is anything wrong tell me
[image: Screenshot_4.png]

‫في الأربعاء، 29 ديسمبر 2021 في 2:03 ص تمت كتابة ما يلي بواسطة ‪Ighor
July‬‏ ***@***.***‬‏>:‬

**Comment by m2m4m6m8m10** [comment]
it was like this since i usd it
is there anything wrong
i know about normal trading
but i want to know if rules group is trading or not
and please if there is anything wrong tell me
![Screenshot_4](https://user-images.githubusercontent.com/96547465/147705204-72781079-e9ed-42ba-b65d-bac3de240db6.png)

**Comment by m2m4m6m8m10** [comment]
it was like this since i usd it
is there anything wrong
i know about normal trading
but i want to know if rules group is trading or not
and please if there is anything wrong tell me
![Screenshot_5](https://user-images.githubusercontent.com/96547465/147706214-7f9c699d-4832-4ab7-8921-0e00361c8952.png)

**Comment by JulyIghor** [comment]
> it was like this since i usd it
> is there anything wrong
> i know about normal trading
> but i want to know if rules group is trading or not
> and please if there is anything wrong tell me

Of course rules made for trading. You can see the error code, most likely you don't have enough balance

**Comment by m2m4m6m8m10** [comment]
can you please tell me how you are trade in qt bitcoin not
because i have balance about $6.5 worth of bitcoin

> > it was like this since i usd it
> > is there anything wrong
> > i know about normal trading
> > but i want to know if rules group is trading or not
> > and please if there is anything wrong tell me
> 
> Of course rules made for trading. You can see the error code, most likely you don't have enough balance

**Comment by m2m4m6m8m10** [comment]
> > it was like this since i usd it
> > is there anything wrong
> > i know about normal trading
> > but i want to know if rules group is trading or not
> > and please if there is anything wrong tell me
> 
> Of course rules made for trading. You can see the error code, most likely you don't have enough balance

can you please tell me how you are trade in qt bitcoin not
because i have balance about $6.5 worth of bitcoin
please give an example of how you fill rule
![Screenshot_6](https://user-images.githubusercontent.com/96547465/147713865-9d2adeb8-8ec0-4e4f-bed0-d4fa75ed36f0.png)

**Comment by m2m4m6m8m10** [comment]
> > it was like this since i usd it
> > is there anything wrong
> > i know about normal trading
> > but i want to know if rules group is trading or not
> > and please if there is anything wrong tell me
> 
> Of course rules made for trading. You can see the error code, most likely you don't have enough balance

**Comment by JulyIghor** [comment]
> can you please tell me how you are trade in qt bitcoin bot

You have to understand logic of your strategy, and if you don't know what to do there, you may loose money.

**Comment by m2m4m6m8m10** [comment]
can you please give me method to use in rules group in qt bitcoin trade
as example : my sell order or me buy order executed immediately when market
order sold or bought
please help with this issue
